### ISSUE TITLE
Generate appropriate open data licence list for `model-metadata-schema.json`

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubTemplate#4]
We need a list of valid licenses appropriate for licensing data allowing use of derivatives.

Given hub maintainers will ultimately develop this schema for their hub and use it to validate submitted `model-metadata.json` files, this only need to be a reasonable starting point that hub maintainers will be free to adapt to allow for a smaller or larger list of licenses for data submitted to their hub.

**Comment by annakrystalli** [comment]
### Resources:
- https://opendatacommons.org/licenses/
- https://creativecommons.org/about/program-areas/open-data/
- https://theodi.org/article/publishers-guide-to-open-data-licensing/
- https://theodi2022.wpengine.com/article/reusers-guide-to-open-data-licensing/


### LICENSE LIST

#### Creative Commons
-  [**CC0-1.0**](https://creativecommons.org/share-your-work/public-domain/cc0) : Creative Commons Zero 1.0 (public domain, “No Rights Reserved”)
- [**CC-BY-4.0**](https://creativecommons.org/licenses/by/4.0/):  Creative Commons Attribution 4.0 International (attribution)
- [**CC-BY_SA-4.0**](https://creativecommons.org/licenses/by-sa/4.0/):  Creative Commons Attribution-ShareAlike 4.0 International (attribution & share-alike)

#### [Open Data Commons](http://opendatacommons.org/) (for Data/Databases)
- [**PPDL**](https://opendatacommons.org/licenses/pddl/): Open Data Commons Public Domain Dedication and License (public domain)
- [**ODC-By**](https://opendatacommons.org/licenses/by/): Open Data Commons Attribution License (attribution)
- [**ODbL**](https://opendatacommons.org/licenses/odbl/): Open Data Commons Open Database License (attribution & share-alike)

#### Government Licenses
- [**OGL-3.0**](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/): UK Open Government License (attribution) ([More info](https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/open-government-licence/))

**Comment by annakrystalli** [comment]
I note that the list of licenses provided by @nickreich here: https://github.com/reichlab/covid19-forecast-hub/blob/master/code/validation/accepted-licenses.csv contains primarily Software Licenses (apart from the Creative Commons entries) which are not appropriate for data. 

In the list compiled below, have also removed any licenses that do not permit derivatives or non commercial use (e.g. CC-BY-ND-NC 4.0)

**Comment by annakrystalli** [comment]
### LICENSE LIST

#### Creative Commons
-  [**CC0-1.0**](https://creativecommons.org/share-your-work/public-domain/cc0) : Creative Commons Zero 1.0 (public domain, “No Rights Reserved”)
- [**CC-BY-4.0**](https://creativecommons.org/licenses/by/4.0/):  Creative Commons Attribution 4.0 International (attribution)
- [**CC-BY_SA-4.0**](https://creativecommons.org/licenses/by-sa/4.0/):  Creative Commons Attribution-ShareAlike 4.0 International (attribution & share-alike)

#### [Open Data Commons](http://opendatacommons.org/) (for Data/Databases)
- [**PPDL**](https://opendatacommons.org/licenses/pddl/): Open Data Commons Public Domain Dedication and License (public domain)
- [**ODC-By**](https://opendatacommons.org/licenses/by/): Open Data Commons Attribution License (attribution)
- [**ODbL**](https://opendatacommons.org/licenses/odbl/): Open Data Commons Open Database License (attribution & share-alike)

#### Government Licenses
- [**OGL-3.0**](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/): UK Open Government License (attribution) ([More info](https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/open-government-licence/))

**Comment by nickreich** [comment]
Thank you for taking the time to think through this carefully. I think your proposed list is good, and I'm ok proceeding with it.  maybe we could also find a place (in the documentation site?) to document the thinking behind the proposed list (with your resources linked) and also make it clear that teams could for whatever reason add their own to this list. But honestly, I think most hub organizers would just be happy to have a resource to point to that justifies a list. (I certainly would have been, a few years back!)
